ynabsplitter:
  dry-run: true
  host: http://localhost:${server.port}
  notifications: # set in prod
    public-key:
    private-key:

spring:
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
