/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.model;

import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BudgetSummaryResponse
 */

public class BudgetSummaryWrapper {
  @JsonProperty("budgets")
  private List<BudgetSummary> budgets = null;

  public BudgetSummaryWrapper data(List<BudgetSummary> budgets) {
    this.budgets = budgets;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(required = true, description = "")
  public List<BudgetSummary> getBudgets() {
    return budgets;
  }

  public void setBudgets(List<BudgetSummary> budgets) {
    this.budgets = budgets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetSummaryWrapper budgetSummaryResponse = (BudgetSummaryWrapper) o;
    return Objects.equals(this.budgets, budgetSummaryResponse.budgets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetSummaryWrapper {\n");
    
    sb.append("    data: ").append(toIndentedString(budgets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
