/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.model;

import java.util.Objects;
import java.util.Arrays;
import ch.excape.ynabclient.model.SaveTransaction;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * SaveTransactionsWrapper
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-07T14:51:52.476+02:00[Europe/Zurich]")
public class SaveTransactionsWrapper {
  @JsonProperty("transaction")
  private SaveTransaction transaction = null;

  @JsonProperty("transactions")
  private List<SaveTransaction> transactions = null;

  public SaveTransactionsWrapper transaction(SaveTransaction transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @Schema(description = "")
  public SaveTransaction getTransaction() {
    return transaction;
  }

  public void setTransaction(SaveTransaction transaction) {
    this.transaction = transaction;
  }

  public SaveTransactionsWrapper transactions(List<SaveTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public SaveTransactionsWrapper addTransactionsItem(SaveTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<SaveTransaction>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Get transactions
   * @return transactions
  **/
  @Schema(description = "")
  public List<SaveTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<SaveTransaction> transactions) {
    this.transactions = transactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveTransactionsWrapper saveTransactionsWrapper = (SaveTransactionsWrapper) o;
    return Objects.equals(this.transaction, saveTransactionsWrapper.transaction) &&
        Objects.equals(this.transactions, saveTransactionsWrapper.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transaction, transactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveTransactionsWrapper {\n");
    
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
