/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SaveMonthCategory
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-06T11:46:19.985416+02:00[Europe/Zurich]")
public class SaveMonthCategory {
  @JsonProperty("budgeted")
  private Long budgeted = null;

  public SaveMonthCategory budgeted(Long budgeted) {
    this.budgeted = budgeted;
    return this;
  }

   /**
   * Budgeted amount in milliunits format
   * @return budgeted
  **/
  @Schema(required = true, description = "Budgeted amount in milliunits format")
  public Long getBudgeted() {
    return budgeted;
  }

  public void setBudgeted(Long budgeted) {
    this.budgeted = budgeted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveMonthCategory saveMonthCategory = (SaveMonthCategory) o;
    return Objects.equals(this.budgeted, saveMonthCategory.budgeted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgeted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveMonthCategory {\n");
    
    sb.append("    budgeted: ").append(toIndentedString(budgeted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
