/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.model;

import java.util.Objects;
import java.util.Arrays;
import ch.excape.ynabclient.model.ScheduledSubTransaction;
import ch.excape.ynabclient.model.ScheduledTransactionSummary;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.LocalDate;
/**
 * ScheduledTransactionDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-06T11:46:19.985416+02:00[Europe/Zurich]")
public class ScheduledTransactionDetail extends ScheduledTransactionSummary {
  @JsonProperty("account_name")
  private String accountName = null;

  @JsonProperty("payee_name")
  private String payeeName = null;

  @JsonProperty("category_name")
  private String categoryName = null;

  @JsonProperty("subtransactions")
  private List<ScheduledSubTransaction> subtransactions = new ArrayList<ScheduledSubTransaction>();

  public ScheduledTransactionDetail accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @Schema(required = true, description = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public ScheduledTransactionDetail payeeName(String payeeName) {
    this.payeeName = payeeName;
    return this;
  }

   /**
   * Get payeeName
   * @return payeeName
  **/
  @Schema(description = "")
  public String getPayeeName() {
    return payeeName;
  }

  public void setPayeeName(String payeeName) {
    this.payeeName = payeeName;
  }

  public ScheduledTransactionDetail categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Get categoryName
   * @return categoryName
  **/
  @Schema(description = "")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public ScheduledTransactionDetail subtransactions(List<ScheduledSubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
    return this;
  }

  public ScheduledTransactionDetail addSubtransactionsItem(ScheduledSubTransaction subtransactionsItem) {
    this.subtransactions.add(subtransactionsItem);
    return this;
  }

   /**
   * If a split scheduled transaction, the subtransactions.
   * @return subtransactions
  **/
  @Schema(required = true, description = "If a split scheduled transaction, the subtransactions.")
  public List<ScheduledSubTransaction> getSubtransactions() {
    return subtransactions;
  }

  public void setSubtransactions(List<ScheduledSubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledTransactionDetail scheduledTransactionDetail = (ScheduledTransactionDetail) o;
    return Objects.equals(this.accountName, scheduledTransactionDetail.accountName) &&
        Objects.equals(this.payeeName, scheduledTransactionDetail.payeeName) &&
        Objects.equals(this.categoryName, scheduledTransactionDetail.categoryName) &&
        Objects.equals(this.subtransactions, scheduledTransactionDetail.subtransactions) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, payeeName, categoryName, subtransactions, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledTransactionDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    payeeName: ").append(toIndentedString(payeeName)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    subtransactions: ").append(toIndentedString(subtransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
