/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.api;

import org.junit.Ignore;
import org.junit.Test;

import ch.excape.ynabclient.model.BudgetDetailResponse;
import ch.excape.ynabclient.model.BudgetSettingsResponse;
import ch.excape.ynabclient.model.BudgetSummaryResponse;

/**
 * API tests for BudgetsApi
 */
@Ignore
public class BudgetsApiTest {

    private final BudgetsApi api = new BudgetsApi();

    /**
     * Single budget
     *
     * Returns a single budget with all related entities.  This resource is effectively a full budget export.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBudgetByIdTest() {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        BudgetDetailResponse response = api.getBudgetById(budgetId, lastKnowledgeOfServer);

        // TODO: test validations
    }
    /**
     * Budget Settings
     *
     * Returns settings for a budget
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBudgetSettingsByIdTest() {
        String budgetId = null;
        BudgetSettingsResponse response = api.getBudgetSettingsById(budgetId);

        // TODO: test validations
    }
    /**
     * List budgets
     *
     * Returns budgets list with summary information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBudgetsTest() {
        BudgetSummaryResponse response = api.getBudgets(false);

        // TODO: test validations
    }
}
