/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.api;

import ch.excape.ynabclient.model.CategoriesResponse;
import ch.excape.ynabclient.model.CategoryResponse;
import ch.excape.ynabclient.model.ErrorResponse;
import org.threeten.bp.LocalDate;
import ch.excape.ynabclient.model.SaveCategoryResponse;
import ch.excape.ynabclient.model.SaveMonthCategoryWrapper;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    /**
     * List categories
     *
     * Returns all categories grouped by category group.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoriesTest() {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        CategoriesResponse response = api.getCategories(budgetId, lastKnowledgeOfServer);

        // TODO: test validations
    }
    /**
     * Single category
     *
     * Returns a single category.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoryByIdTest() {
        String budgetId = null;
        String categoryId = null;
        CategoryResponse response = api.getCategoryById(budgetId, categoryId);

        // TODO: test validations
    }
    /**
     * Single category for a specific budget month
     *
     * Returns a single category for a specific budget month.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMonthCategoryByIdTest() {
        String budgetId = null;
        LocalDate month = null;
        String categoryId = null;
        CategoryResponse response = api.getMonthCategoryById(budgetId, month, categoryId);

        // TODO: test validations
    }
    /**
     * Update a category for a specific month
     *
     * Update a category for a specific month
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateMonthCategoryTest() {
        SaveMonthCategoryWrapper body = null;
        String budgetId = null;
        LocalDate month = null;
        String categoryId = null;
        SaveCategoryResponse response = api.updateMonthCategory(body, budgetId, month, categoryId);

        // TODO: test validations
    }
}
