/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.api;

import ch.excape.ynabclient.model.BulkResponse;
import ch.excape.ynabclient.model.BulkTransactions;
import ch.excape.ynabclient.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeprecatedApi
 */
@Ignore
public class DeprecatedApiTest {

    private final DeprecatedApi api = new DeprecatedApi();

    /**
     * Bulk create transactions
     *
     * Creates multiple transactions.  Although this endpoint is still supported, it is recommended to use &#x27;POST /budgets/{budget_id}/transactions&#x27; to create multiple transactions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bulkCreateTransactionsTest() {
        BulkTransactions body = null;
        String budgetId = null;
        BulkResponse response = api.bulkCreateTransactions(body, budgetId);

        // TODO: test validations
    }
}
