/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.excape.ynabclient.api;

import ch.excape.ynabclient.model.ErrorResponse;
import ch.excape.ynabclient.model.ScheduledTransactionResponse;
import ch.excape.ynabclient.model.ScheduledTransactionsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScheduledTransactionsApi
 */
@Ignore
public class ScheduledTransactionsApiTest {

    private final ScheduledTransactionsApi api = new ScheduledTransactionsApi();

    /**
     * Single scheduled transaction
     *
     * Returns a single scheduled transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScheduledTransactionByIdTest() {
        String budgetId = null;
        String scheduledTransactionId = null;
        ScheduledTransactionResponse response = api.getScheduledTransactionById(budgetId, scheduledTransactionId);

        // TODO: test validations
    }
    /**
     * List scheduled transactions
     *
     * Returns all scheduled transactions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScheduledTransactionsTest() {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        ScheduledTransactionsResponse response = api.getScheduledTransactions(budgetId, lastKnowledgeOfServer);

        // TODO: test validations
    }
}
