name: Cypress E2E tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          working-directory: frontend
          start: npm run cy:start-server
